/*jshint esversion: 6 */
export const STAR_CONTACT = "STAR_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const UNSTAR_CONTACT = "UNSTAR_CONTACT";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const MARK_TO_DELETE = "MARK_TO_DELETE";
export const SHOW_NEW_MODAL = "SHOW_NEW_MODAL";
export const HIDE_NEW_MODAL = "HIDE_NEW_MODAL";
export const SHOW_EDIT_MODAL = "SHOW_EDIT_MODAL";
export const HIDE_EDIT_MODAL = "HIDE_EDIT_MODAL";
export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";
export const ACTIVE_SIDEBAR_LINK = "ACTIVE_SIDEBAR_LINK";
export const DELETE_MULTIPLE_CONTACT = "DELETE_MULTIPLE_CONTACT";
export const HANDLE_NEW_CONTACT_SUBMIT = "HANDLE_NEW_CONTACT_SUBMIT";
