/*jshint esversion: 6 */
export const STAR_CONTACT = "STAR_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const UNSTAR_CONTACT = "UNSTAR_CONTACT";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const MARK_TO_DELETE = "MARK_TO_DELETE";
export const ACTIVE_SIDEBAR_LINK = "ACTIVE_SIDEBAR_LINK";
export const DELETE_MULTIPLE_CONTACT = "DELETE_MULTIPLE_CONTACT";
