export const FETCH_TREND = "FETCH_TREND";
export const FETCH_TRENDS = "FETCH_TRENDS";
export const FETCH_CLASSIFICATION = "FETCH_CLASSIFICATION";
export const UPDATE_CLASSIFICATION_LIKE = "UPDATE_CLASSIFICATION_LIKE";
export const UPDATE_TREND_LIKES = "UPDATE_TREND_LIKES";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_BLOG_SEARCH = "TOGGLE_BLOG_SEARCH";
